<?xml version='1.0' encoding='utf-8'?><PEFACTION><!--type 0图片，1，TGA-->
<CGAction Left='0.00' Right='973.36' Width='1919.56' Height='106.64' Type='0'>

<FileName>x:\cpu\image\20160629\20161028809999.jpg</FileName>
</CGAction><!--type 0图片，1，TGA--><CGAction Left='1643.65' Right='78.83' Width='197.08' Height='157.66' Type='1'>
<FileName>x:\cpu\image\20160629\20161028809999.jpg</FileName></CGAction>
<!--Type 0.台标遮罩--><FXAction Left='78.83' Right='78.83' Width='197.08' Height='157.66' Type='0'><FileName></FileName></FXAction></PEFACTION>